FROM python:3.12-slim-bookworm

# Install dependencies, including zsh
RUN apt update && apt upgrade -y && \
    apt install -y gcc git wget curl less unzip zsh git-lfs && \
    pip install --no-cache-dir "pip==26.1.1" && \
    pip install --no-cache-dir "uv==0.12.22"

# Install Oh My Zsh without using chsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended || true
RUN sed -i 's/ZSH_THEME=".*"/ZSH_THEME="xiong-chiamiov-plus"/' /root/.zshrc

# set default shell
SHELL ["/bin/zsh", "-c"]

# Set working directory
WORKDIR /

# Copy and install requirements
COPY requirements.txt requirements.txt
RUN uv pip sync requirements.txt --system
